version: '3.9'

services:
  teable:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app:delegated        # Live sync your code
      - /app/node_modules       # Don't overwrite container node_modules
    command: pnpm dev           # Use your dev startup command
    environment:
      - NODE_ENV=development
      - TZ=${TIMEZONE}
      - NEXT_ENV_IMAGES_ALL_REMOTE=true
    depends_on:
      teable-db:
        condition: service_healthy
    networks:
      - teable-standalone

  teable-db:
    ports:
      - '42345:5432'
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data:rw  # Use host directory for persistent DB

volumes:
  teable-data:
  teable-db:

networks:
  teable-standalone:
    name: teable-standalone-network
    driver: bridge
